### ISSUE TITLE
Fail to convert lightgbm to pmml （IndexOutOfBoundsException）

### ISSUE THREAD

**Issue by sp910** [jpmml/jpmml-lightgbm#22]
when I run java -jar jpmml-lightgbm-executable-1.2-SNAPSHOT.jar --lgbm-input aa.txt --pmml-output lightgbm.pmml to convert lightgbm model to pmml format, but encountered, 

Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
        at java.util.ArrayList.rangeCheck(ArrayList.java:657)
        at java.util.ArrayList.get(ArrayList.java:433)
        at org.jpmml.lightgbm.Tree.selectValues(Tree.java:244)
        at org.jpmml.lightgbm.Tree.encodeNode(Tree.java:155)
        at org.jpmml.lightgbm.Tree.encodeNode(Tree.java:191)
        at org.jpmml.lightgbm.Tree.encodeNode(Tree.java:191)
        at org.jpmml.lightgbm.Tree.encodeNode(Tree.java:191)
        at org.jpmml.lightgbm.Tree.encodeTreeModel(Tree.java:94)
        at org.jpmml.lightgbm.ObjectiveFunction.createMiningModel(ObjectiveFunction.java:66)
        at org.jpmml.lightgbm.BinomialLogisticRegression.encodeMiningModel(BinomialLogisticRegression.java:48)
        at org.jpmml.lightgbm.GBDT.encodeMiningModel(GBDT.java:285)
        at org.jpmml.lightgbm.GBDT.encodePMML(GBDT.java:274)
        at org.jpmml.lightgbm.Main.run(Main.java:131)
        at org.jpmml.lightgbm.Main.main(Main.java:117)

Attached is the lightgbm model file.
[aa.txt](https://github.com/jpmml/jpmml-lightgbm/files/3068911/aa.txt)

lightgbm version is 2.2.3

Can someone please kindly help? Thanks much!

**Comment by vruusmann** [comment]
The model file (aa.txt) appears to contain a `pandas_categorical` section, which confuses the current parser code:
https://github.com/jpmml/jpmml-lightgbm/blob/master/src/main/java/org/jpmml/lightgbm/GBDT.java#L422-L466

Does the conversion succeed if you simplify category levels?

**Comment by sp910** [comment]
I found it will be success when I use more data  traing，but with not simplify category levels.

Attached file can be convert  succeed, but I didn't simplify category levels.
[gbm_3yr.txt](https://github.com/jpmml/jpmml-lightgbm/files/3069241/gbm_3yr.txt)

**Comment by 77QingLiu** [comment]
I also encounter this error, could you please explain how to simplify category levels?

**Comment by yairdata** [comment]
happened to me on 1.3.0 version
i use the pandas_categorical because i want the categorical values to be interpreted as string and not be converted to Integers.
the following code makes throw the IndexOutOfBoundsException error :

`int n = (this.cat_boundaries_[cat_idx + 1] - this.cat_boundaries_[cat_idx]);

		for(int i = 0; i < n; i++){

			for(int j = 0; j < 32; j++){
				int cat = (i * 32) + j;

				if(findInBitset(this.cat_threshold_, this.cat_boundaries_[cat_idx], n, cat)){
					Object value;

					if(indexAsValue){
						value = cat;
					} else

					{
						value = values.get(cat);
					} // End if`

i can't work with the integers because the performance is worse when it works with integers , and because of inference issues regarding conversion in runtime to integers. (sklearn pipeline had other issues)

**Comment by etveritas** [comment]
> I also encounter this error, could you please explain how to simplify category levels?

Me too

**Comment by etveritas** [comment]
@vruusmann I hava category and continuouse feature both in lightgbm model, and I encounter this error.Could you please explain how to simplify category levels?

**Comment by jean-jm** [comment]
me too

**Comment by vruusmann** [comment]
> me too

Too bad, but I can't help you.

You have full access to your LightGBM model file, and my JPMML-LightGBM source code. Feel free to fix the issue, and submit a corrective patch back to the project.

**Comment by jean-jm** [comment]
this code has some problems ,so that it will throw error like "outofsize"


------------------ 原始邮件 ------------------
发件人:                                                                                                                        "jpmml/jpmml-lightgbm"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月23日(星期四) 下午4:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jpmml/jpmml-lightgbm] Fail to convert lightgbm to pmml （IndexOutOfBoundsException） (#22)





  
me too
  
Too bad, but I can't help you.
 
You have full access to your LightGBM model file, and my JPMML-LightGBM source code. Feel free to fix the issue, and submit a corrective patch back to the project.

**Comment by vruusmann** [comment]
> this code has some problems ..

@jean-jm This is not an actionable bug report.

Please provide a reproducible example (a LightGBM model object, which fails to convert using the latest JPMML-LightGBM version 1.4.6), or work on this on your own.

Please note that I don't need your actual proprietary LightGBM model object. You can train one from scratch, using some toy dataset (eg. "iris").

**Comment by jean-jm** [comment]
3q! this txt file can be reproducible, looking forward to your reply!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jpmml/jpmml-lightgbm"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月23日(星期四) 晚上7:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jpmml/jpmml-lightgbm] Fail to convert lightgbm to pmml （IndexOutOfBoundsException） (#22)





  
this code has some problems ..
  
@jean-jm This is not an actionable bug report.
 
Please provide a reproducible example (a LightGBM model object, which fails to convert using the latest JPMML-LightGBM version 1.4.6), or work on this on your own.
 
Please note that I don't need your actual proprietary LightGBM model object. You can train one from scratch, using some toy dataset (eg. "iris").

**Comment by jean-jm** [comment]
[test2jm_light_dataset1_20231117_v1.txt.zip](https://github.com/jpmml/jpmml-lightgbm/files/13450021/test2jm_light_dataset1_20231117_v1.txt.zip)
this file can be used, thank you so much, looking forward to your reply.

**Comment by vruusmann** [comment]
@jean-jm Let's continue here: https://github.com/jpmml/jpmml-lightgbm/issues/62

Your issue looks new/different from what was discussed here originally.
